#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    extern FILE *yyin;
    extern int yylineno;
    extern int yylex();
    void yyerror(const char *s);

#line 14 "parser.y"
typedef union {
    int iconst;       /* For integer constants */
    float fconst;     /* For real constants */
    char* sconst;     /* For string literals */
    char* ident;      /* For identifiers */
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	STRING_LITERAL	258
#define	PLUS	259
#define	MINUS	260
#define	MULT	261
#define	DIV	262
#define	COMMENT	263
#define	ASSIGNMENT	264
#define	RANGE	265
#define	COLON	266
#define	SEMICOLON	267
#define	EQ	268
#define	NEQ	269
#define	LT	270
#define	LTE	271
#define	GT	272
#define	GTE	273
#define	IMPLICATION	274
#define	AND	275
#define	OR	276
#define	XOR	277
#define	NOT	278
#define	VAR	279
#define	IS	280
#define	THEN	281
#define	EMPTY	282
#define	END	283
#define	FUNCTION	284
#define	IN	285
#define	LOOP	286
#define	FOR	287
#define	WHILE	288
#define	IF	289
#define	ELSE	290
#define	TRUE	291
#define	FALSE	292
#define	RETURN	293
#define	INT	294
#define	REAL	295
#define	BOOL	296
#define	STRING	297
#define	INT_LITERAL	298
#define	REAL_LITERAL	299
#define	IDENTIFIER	300
#define	LEFT_BR	301
#define	RIGHT_BR	302
#define	DOT	303
#define	LEFT_SQ_BR	304
#define	RIGHT_SQ_BR	305
#define	COMMA	306
#define	QUOTE	307
#define	INVALID_CHARACTER	308
#define	PRINT	309
#define	RIGHT_CURL_BR	310
#define	LEFT_CURL_BR	311


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int STRING_LITERAL;
static const int PLUS;
static const int MINUS;
static const int MULT;
static const int DIV;
static const int COMMENT;
static const int ASSIGNMENT;
static const int RANGE;
static const int COLON;
static const int SEMICOLON;
static const int EQ;
static const int NEQ;
static const int LT;
static const int LTE;
static const int GT;
static const int GTE;
static const int IMPLICATION;
static const int AND;
static const int OR;
static const int XOR;
static const int NOT;
static const int VAR;
static const int IS;
static const int THEN;
static const int EMPTY;
static const int END;
static const int FUNCTION;
static const int IN;
static const int LOOP;
static const int FOR;
static const int WHILE;
static const int IF;
static const int ELSE;
static const int TRUE;
static const int FALSE;
static const int RETURN;
static const int INT;
static const int REAL;
static const int BOOL;
static const int STRING;
static const int INT_LITERAL;
static const int REAL_LITERAL;
static const int IDENTIFIER;
static const int LEFT_BR;
static const int RIGHT_BR;
static const int DOT;
static const int LEFT_SQ_BR;
static const int RIGHT_SQ_BR;
static const int COMMA;
static const int QUOTE;
static const int INVALID_CHARACTER;
static const int PRINT;
static const int RIGHT_CURL_BR;
static const int LEFT_CURL_BR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,STRING_LITERAL=258
	,PLUS=259
	,MINUS=260
	,MULT=261
	,DIV=262
	,COMMENT=263
	,ASSIGNMENT=264
	,RANGE=265
	,COLON=266
	,SEMICOLON=267
	,EQ=268
	,NEQ=269
	,LT=270
	,LTE=271
	,GT=272
	,GTE=273
	,IMPLICATION=274
	,AND=275
	,OR=276
	,XOR=277
	,NOT=278
	,VAR=279
	,IS=280
	,THEN=281
	,EMPTY=282
	,END=283
	,FUNCTION=284
	,IN=285
	,LOOP=286
	,FOR=287
	,WHILE=288
	,IF=289
	,ELSE=290
	,TRUE=291
	,FALSE=292
	,RETURN=293
	,INT=294
	,REAL=295
	,BOOL=296
	,STRING=297
	,INT_LITERAL=298
	,REAL_LITERAL=299
	,IDENTIFIER=300
	,LEFT_BR=301
	,RIGHT_BR=302
	,DOT=303
	,LEFT_SQ_BR=304
	,RIGHT_SQ_BR=305
	,COMMA=306
	,QUOTE=307
	,INVALID_CHARACTER=308
	,PRINT=309
	,RIGHT_CURL_BR=310
	,LEFT_CURL_BR=311


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::STRING_LITERAL=258;
const int YY_parse_CLASS::PLUS=259;
const int YY_parse_CLASS::MINUS=260;
const int YY_parse_CLASS::MULT=261;
const int YY_parse_CLASS::DIV=262;
const int YY_parse_CLASS::COMMENT=263;
const int YY_parse_CLASS::ASSIGNMENT=264;
const int YY_parse_CLASS::RANGE=265;
const int YY_parse_CLASS::COLON=266;
const int YY_parse_CLASS::SEMICOLON=267;
const int YY_parse_CLASS::EQ=268;
const int YY_parse_CLASS::NEQ=269;
const int YY_parse_CLASS::LT=270;
const int YY_parse_CLASS::LTE=271;
const int YY_parse_CLASS::GT=272;
const int YY_parse_CLASS::GTE=273;
const int YY_parse_CLASS::IMPLICATION=274;
const int YY_parse_CLASS::AND=275;
const int YY_parse_CLASS::OR=276;
const int YY_parse_CLASS::XOR=277;
const int YY_parse_CLASS::NOT=278;
const int YY_parse_CLASS::VAR=279;
const int YY_parse_CLASS::IS=280;
const int YY_parse_CLASS::THEN=281;
const int YY_parse_CLASS::EMPTY=282;
const int YY_parse_CLASS::END=283;
const int YY_parse_CLASS::FUNCTION=284;
const int YY_parse_CLASS::IN=285;
const int YY_parse_CLASS::LOOP=286;
const int YY_parse_CLASS::FOR=287;
const int YY_parse_CLASS::WHILE=288;
const int YY_parse_CLASS::IF=289;
const int YY_parse_CLASS::ELSE=290;
const int YY_parse_CLASS::TRUE=291;
const int YY_parse_CLASS::FALSE=292;
const int YY_parse_CLASS::RETURN=293;
const int YY_parse_CLASS::INT=294;
const int YY_parse_CLASS::REAL=295;
const int YY_parse_CLASS::BOOL=296;
const int YY_parse_CLASS::STRING=297;
const int YY_parse_CLASS::INT_LITERAL=298;
const int YY_parse_CLASS::REAL_LITERAL=299;
const int YY_parse_CLASS::IDENTIFIER=300;
const int YY_parse_CLASS::LEFT_BR=301;
const int YY_parse_CLASS::RIGHT_BR=302;
const int YY_parse_CLASS::DOT=303;
const int YY_parse_CLASS::LEFT_SQ_BR=304;
const int YY_parse_CLASS::RIGHT_SQ_BR=305;
const int YY_parse_CLASS::COMMA=306;
const int YY_parse_CLASS::QUOTE=307;
const int YY_parse_CLASS::INVALID_CHARACTER=308;
const int YY_parse_CLASS::PRINT=309;
const int YY_parse_CLASS::RIGHT_CURL_BR=310;
const int YY_parse_CLASS::LEFT_CURL_BR=311;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		150
#define	YYFLAG		-32768
#define	YYNTBASE	57

#define YYTRANSLATE(x) ((unsigned)(x) <= 311 ? yytranslate[x] : 97)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     8,     9,    14,    16,    17,    20,    21,
    23,    27,    29,    31,    33,    35,    39,    41,    43,    45,
    47,    49,    51,    53,    57,    59,    61,    63,    67,    69,
    71,    75,    77,    81,    83,    85,    87,    88,    91,    92,
    95,    97,    99,   101,   104,   107,   111,   115,   116,   118,
   122,   123,   125,   127,   129,   131,   133,   137,   141,   144,
   145,   148,   150,   151,   158,   161,   162,   166,   172,   176,
   178,   180,   182,   184,   186,   189,   192,   194,   198,   200,
   202,   204,   206,   208,   210,   212,   214,   218,   222,   224,
   228,   229,   232,   235,   236,   242,   244,   248,   249,   253,
   256,   258,   260
};

static const short yyrhs[] = {    58,
     0,    58,    59,     0,    58,    76,     0,     0,    24,    45,
    61,    60,     0,    12,     0,     0,     9,    62,     0,     0,
    64,     0,    62,    63,    64,     0,    20,     0,    21,     0,
    22,     0,    66,     0,    64,    65,    66,     0,    15,     0,
    16,     0,    17,     0,    18,     0,    13,     0,    14,     0,
    68,     0,    66,    67,    68,     0,     4,     0,     5,     0,
    70,     0,    68,    69,    70,     0,     6,     0,     7,     0,
    71,    73,    72,     0,    87,     0,    46,    62,    47,     0,
     4,     0,     5,     0,    23,     0,     0,    25,    86,     0,
     0,    45,    74,     0,    36,     0,    37,     0,     3,     0,
    48,    43,     0,    48,    45,     0,    49,    62,    50,     0,
    46,    75,    47,     0,     0,    62,     0,    75,    51,    62,
     0,     0,    77,     0,    78,     0,    80,     0,    82,     0,
    84,     0,    73,     9,    62,     0,    54,    62,    79,     0,
    51,    62,     0,     0,    38,    81,     0,    62,     0,     0,
    34,    62,    26,    96,    83,    28,     0,    35,    96,     0,
     0,    33,    62,    85,     0,    32,    45,    30,    86,    85,
     0,    31,    96,    28,     0,    39,     0,    40,     0,    41,
     0,    42,     0,    27,     0,    49,    50,     0,    46,    47,
     0,    29,     0,    62,    10,    62,     0,    43,     0,    44,
     0,    36,     0,    37,     0,     3,     0,    88,     0,    89,
     0,    93,     0,    49,    75,    50,     0,    56,    90,    55,
     0,    91,     0,    90,    51,    91,     0,     0,    92,    62,
     0,    45,     9,     0,     0,    29,    46,    94,    47,    95,
     0,    45,     0,    94,    51,    45,     0,     0,    25,    96,
    28,     0,    19,    62,     0,    58,     0,    76,     0,     0,
    76,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    36,    38,    39,    40,    43,    45,    46,    49,    50,    53,
    54,    57,    58,    59,    62,    63,    66,    67,    68,    69,
    70,    71,    74,    75,    78,    79,    82,    83,    86,    87,
    90,    91,    92,    95,    96,    97,    98,   101,   102,   105,
   106,   107,   108,   111,   112,   113,   114,   115,   118,   119,
   120,   123,   124,   125,   126,   127,   130,   132,   134,   135,
   138,   140,   141,   144,   146,   147,   150,   151,   154,   156,
   157,   158,   159,   160,   161,   162,   163,   164,   167,   168,
   169,   170,   171,   172,   173,   174,   177,   179,   181,   182,
   183,   186,   188,   189,   192,   194,   195,   196,   199,   200,
   203,   206,   207
};

static const char * const yytname[] = {   "$","error","$illegal.","STRING_LITERAL",
"PLUS","MINUS","MULT","DIV","COMMENT","ASSIGNMENT","RANGE","COLON","SEMICOLON",
"EQ","NEQ","LT","LTE","GT","GTE","IMPLICATION","AND","OR","XOR","NOT","VAR",
"IS","THEN","EMPTY","END","FUNCTION","IN","LOOP","FOR","WHILE","IF","ELSE","TRUE",
"FALSE","RETURN","INT","REAL","BOOL","STRING","INT_LITERAL","REAL_LITERAL","IDENTIFIER",
"LEFT_BR","RIGHT_BR","DOT","LEFT_SQ_BR","RIGHT_SQ_BR","COMMA","QUOTE","INVALID_CHARACTER",
"PRINT","RIGHT_CURL_BR","LEFT_CURL_BR","Program","DeclarationsAndStatements",
"Declaration","OptSemicolon","OptAssignment","Expression","LogicalOp","Relation",
"RelOp","Factor","AddOp","Term","MulOp","Unary","OptUnary","OptTypeIndicator",
"Primary","OptTail","OptExprList","Statement","Assignment","Print","OptPrintList",
"Return","OptExpression","If","OptElse","Loop","LoopBody","TypeIndicator","Literal",
"ArrayLiteral","TupleLiteral","OptTupleExprList","TupleElement","OptIdentifierAssignment",
"FunctionLiteral","OptIdentifierList","FunBody","Body",""
};
#endif

static const short yyr1[] = {     0,
    57,    58,    58,    58,    59,    60,    60,    61,    61,    62,
    62,    63,    63,    63,    64,    64,    65,    65,    65,    65,
    65,    65,    66,    66,    67,    67,    68,    68,    69,    69,
    70,    70,    70,    71,    71,    71,    71,    72,    72,    73,
    73,    73,    73,    74,    74,    74,    74,    74,    75,    75,
    75,    76,    76,    76,    76,    76,    77,    78,    79,    79,
    80,    81,    81,    82,    83,    83,    84,    84,    85,    86,
    86,    86,    86,    86,    86,    86,    86,    86,    87,    87,
    87,    87,    87,    87,    87,    87,    88,    89,    90,    90,
    90,    91,    92,    92,    93,    94,    94,    94,    95,    95,
    96,    -1,    -1
};

static const short yyr2[] = {     0,
     1,     2,     2,     0,     4,     1,     0,     2,     0,     1,
     3,     1,     1,     1,     1,     3,     1,     1,     1,     1,
     1,     1,     1,     3,     1,     1,     1,     3,     1,     1,
     3,     1,     3,     1,     1,     1,     0,     2,     0,     2,
     1,     1,     1,     2,     2,     3,     3,     0,     1,     3,
     0,     1,     1,     1,     1,     1,     3,     3,     2,     0,
     2,     1,     0,     6,     2,     0,     3,     5,     3,     1,
     1,     1,     1,     1,     2,     2,     1,     3,     1,     1,
     1,     1,     1,     1,     1,     1,     3,     3,     1,     3,
     0,     2,     2,     0,     5,     1,     3,     0,     3,     2,
     1,     1,     2
};

static const short yydefact[] = {     4,
     1,    43,     0,     0,    37,    37,    41,    42,    63,    48,
    37,     2,     0,     3,    52,    53,    54,    55,    56,     9,
     0,    83,    34,    35,    36,     0,    81,    82,    79,    80,
    37,    51,    94,     0,    10,    15,    23,    27,     0,    32,
    84,    85,    86,     0,    62,    61,    51,     0,    37,    40,
    60,    37,    37,     7,    37,    98,     0,    49,     0,     0,
     0,    89,    37,    12,    13,    14,     4,    37,    67,    21,
    22,    17,    18,    19,    20,    37,    25,    26,    37,    29,
    30,    37,    39,     4,     0,    44,    45,     0,    37,    58,
    57,     8,     6,     5,    74,    77,    70,    71,    72,    73,
    37,    37,     0,     0,    96,     0,    33,    87,    37,    93,
    94,    88,    92,   101,     0,    11,    16,    24,    28,    37,
    31,    66,    47,    46,    59,    76,    75,    37,    68,     0,
     0,    50,    90,    69,    38,     4,     0,    78,    37,     4,
    95,    97,    65,    64,   100,     0,    99,     0,     0,     0
};

static const short yydefgoto[] = {   148,
   114,    12,    94,    54,    58,    68,    35,    76,    36,    79,
    37,    82,    38,    39,   121,    13,    50,    59,    14,    15,
    16,    90,    17,    46,    18,   137,    19,    69,   104,    40,
    41,    42,    61,    62,    63,    43,   106,   141,   115
};

static const short yypact[] = {-32768,
   104,-32768,   -43,   -40,   163,   163,-32768,-32768,   116,    54,
   163,-32768,     6,-32768,-32768,-32768,-32768,-32768,-32768,    11,
    21,-32768,-32768,-32768,-32768,    18,-32768,-32768,-32768,-32768,
   163,   116,   -26,    32,   164,    41,    87,-32768,     4,-32768,
-32768,-32768,-32768,    66,    13,-32768,   116,    35,   163,-32768,
   -12,   163,   163,    56,    33,    26,    -4,    13,    59,    72,
   -24,-32768,   163,-32768,-32768,-32768,-32768,   163,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   163,-32768,-32768,   163,-32768,
-32768,   163,    58,-32768,   -19,-32768,-32768,    -8,   163,-32768,
    13,    13,-32768,-32768,-32768,    18,-32768,-32768,-32768,-32768,
   127,    62,     1,    64,-32768,    10,-32768,-32768,   163,-32768,
    45,-32768,    13,   104,    69,   164,    41,    87,-32768,    33,
-32768,    79,-32768,-32768,    13,-32768,-32768,   163,-32768,     5,
    71,    13,-32768,-32768,-32768,-32768,    73,    13,   163,-32768,
-32768,-32768,-32768,-32768,    13,    89,-32768,   122,   124,-32768
};

static const short yypgoto[] = {-32768,
   125,-32768,-32768,-32768,    -5,-32768,    61,-32768,    50,-32768,
    48,-32768,    51,-32768,-32768,    96,-32768,    97,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    39,    27,-32768,
-32768,-32768,-32768,    37,-32768,-32768,-32768,-32768,   -81
};


#define	YYLAST		219


static const short yytable[] = {    34,
    44,    20,   122,    45,    21,    51,     2,    64,    65,    66,
   128,    64,    65,    66,    52,    64,    65,    66,    60,    53,
    64,    65,    66,   139,   -91,    57,   111,   123,   -91,   140,
   112,   109,    64,    65,    66,    22,    23,    24,    89,     7,
     8,   124,   107,    88,    77,    78,    91,    92,    10,   103,
    55,    64,    65,    66,   143,    25,   130,   113,   146,    95,
   131,    96,    67,    56,    22,    23,    24,    93,    27,    28,
   105,    97,    98,    99,   100,    29,    30,    86,   101,    87,
   110,   102,   120,   125,    25,    64,    65,    66,    33,    60,
    26,    84,    80,    81,    67,    57,   134,    27,    28,    47,
   144,    48,    49,   132,    29,    30,     2,    31,   108,   109,
    32,   127,   -51,   136,   103,   142,   147,    33,    22,    23,
    24,   149,   138,   150,     1,   117,   118,     3,   116,    22,
    23,    24,   119,   145,    83,     4,     5,     6,    25,     7,
     8,     9,   129,    85,    26,     0,   135,   133,    10,    25,
     0,    27,    28,     0,     0,    26,     0,    11,    29,    30,
   -37,    31,    27,    28,    32,    22,    23,    24,     0,    29,
    30,    33,    31,   126,     0,    32,    70,    71,    72,    73,
    74,    75,    33,     0,     0,    25,     0,     0,     0,     0,
     0,    26,     0,     0,     0,     0,     0,     0,    27,    28,
     0,     0,     0,     0,     0,    29,    30,     0,    31,     0,
     0,    32,     0,     0,     0,     0,     0,     0,    33
};

static const short yycheck[] = {     5,
     6,    45,    84,     9,    45,    11,     3,    20,    21,    22,
    10,    20,    21,    22,     9,    20,    21,    22,    45,     9,
    20,    21,    22,    19,    51,    31,    51,    47,    55,    25,
    55,    51,    20,    21,    22,     3,     4,     5,    51,    36,
    37,    50,    47,    49,     4,     5,    52,    53,    45,    55,
    30,    20,    21,    22,   136,    23,    47,    63,   140,    27,
    51,    29,    31,    46,     3,     4,     5,    12,    36,    37,
    45,    39,    40,    41,    42,    43,    44,    43,    46,    45,
     9,    49,    25,    89,    23,    20,    21,    22,    56,    45,
    29,    26,     6,     7,    31,   101,    28,    36,    37,    46,
    28,    48,    49,   109,    43,    44,     3,    46,    50,    51,
    49,    50,    51,    35,   120,    45,    28,    56,     3,     4,
     5,     0,   128,     0,     0,    76,    79,    24,    68,     3,
     4,     5,    82,   139,    39,    32,    33,    34,    23,    36,
    37,    38,   104,    47,    29,    -1,   120,   111,    45,    23,
    -1,    36,    37,    -1,    -1,    29,    -1,    54,    43,    44,
    45,    46,    36,    37,    49,     3,     4,     5,    -1,    43,
    44,    56,    46,    47,    -1,    49,    13,    14,    15,    16,
    17,    18,    56,    -1,    -1,    23,    -1,    -1,    -1,    -1,
    -1,    29,    -1,    -1,    -1,    -1,    -1,    -1,    36,    37,
    -1,    -1,    -1,    -1,    -1,    43,    44,    -1,    46,    -1,
    -1,    49,    -1,    -1,    -1,    -1,    -1,    -1,    56
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 210 "parser.y"


void yyerror(const char *s)
{
  fprintf(stderr, "Syntax error at line %d: %s\n", yylineno, s);
  exit(1);
}

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input_file>\n", argv[0]);
        return 1;
    }

    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror(argv[1]);
        return 1;
    }

    if (strcmp(argv[2], "lexer") == 0) {
      int token;
      while ((token = yylex())) {
          // printf("Token: %d\n", token);
      }
    } else {
      int flag = yyparse();
      fprintf(stderr, "Flag %d\n", flag);
    }
    fclose(yyin);

    return 0;
}
